### ISSUE TITLE
Add option for listening mode on HTTP Server (NetleniumServer)

### ISSUE THREAD

**Issue by Netkas** [intellivoid/Netlenium#16]
At the moment no option has been set for changing the listening type for the HTTP Server, by default it's set to listen for requests from any client on the network, by default this should be set to loopback connections only to prevent unauthorized access from other machines

**Comment by ghost** [comment]
@Netkas IMO this port must be permanently switched to loopback listening in localhost/0.0.0.0 at a custom port.

Reasons? Security, more likely.
It's better to use an specialized HTTP server/proxy, such as NGINX, and proxy the requests to the custom port.
That way we can filter a lot of things, and provide a safer, secure, and more controllable solution, plus we don't need to reinvent the whole wheel, but it's safer and certified security-wise.

Advice comes from OWASP Barranquilla/Colombia team after analyzing the current code dedicated to the HTTP server.

**Comment by Netkas** [comment]
The default server is good for local use, as Netlenium is intended to run in the background on a consumer's machine so software that utilizes Netlenium can establish sessions using the default port.

I agree that the server that is currently embedded into the software is not ideal for large-scale production use. NGINX Would be wiser for such cases, but i have no idea how to get started on writing a Netlenium CGI to work with NGINX.

The whole idea of Netlenium being able to be downloaded for free is that it's supposed to give software / scripts access to a sandboxed browser environment to interact with. This keeps the user's personal information & cookies safe from malicious intentions and eliminates the need for messing with Web Drivers or cross-compatibility between different browsers. Therefore that's why Netlenium has it's own embedded HTTP Server with the default port (should be) listening on only loopback connections. (localhost/0.0.0.0) unless configured otherwise by the user using of the command-line options.

But if we wish to achieve the goal of creating a hosting service for Netlenium Servers, the embedded HTTP Server provided within Netlenium will not cut it and there should be ideas on how to get Netlenium working with a NGINX Web Server (Directly or as a proxy)

**Comment by ghost** [comment]
@Netkas You don't need a CGI for that though. NGINX allows you to directly proxy a port in local side.

And yes, this solution is made basically for large-scale, but it'd be good to make it a policy for end customers though. Atleast that's what @owaspbaq advices.

**Comment by Netkas** [comment]
Then a automated process should be written for this, or at least can be accomplished with minimal efforts.

**Comment by Netkas** [comment]
See commit [04ebdcd44aea7d898f1e1f709332bb8da774c145](https://github.com/intellivoid/Netlenium/commit/04ebdcd44aea7d898f1e1f709332bb8da774c145)
