### ISSUE TITLE
Add GitHub Storage Manager to Netlenium.WebAPI

### ISSUE THREAD

**Issue by Netkas** [intellivoid/Netlenium#5]
To add support for other browsers such as Firefox, Stand-alone XULRunner, Opera, Microsoft Edge or even CEF Would require a GitHub Storage Manager to retrieve the latest driver's, compare resource versions and automatic updates

**Comment by ghost** [comment]
@Netkas #bitenginecdn pda

**Comment by Netkas** [comment]
> @Netkas #bitenginecdn pda

Storage Manager for an external resource could work, however that external resource must have the latest resources available when possible.

**Comment by Netkas** [comment]
See [Netlenium.WebAPI.Google](https://github.com/intellivoid/Netlenium/tree/master/Netlenium/Netlenium.WebAPI/Google) as an example of how resources get retrieved from Google Storage. This is used in [Netlenium.Driver.Chrome.DriverManager](https://github.com/intellivoid/Netlenium/blob/master/Netlenium/Netlenium.Driver/Chrome/DriverManager.c)

**Comment by ghost** [comment]
@Netkas pda ok #bitenginecdn

we can use the cdn to forward the res from GS to the user

**Comment by ghost** [comment]
@mdelahozl code review in progress, expect answer at internal email (z********@intellivo.id).

eta 20m

**Comment by libinit** [comment]
> 
> 
> See [Netlenium.WebAPI.Google](https://github.com/intellivoid/Netlenium/tree/master/Netlenium/Netlenium.WebAPI/Google) as an example of how resources get retrieved from Google Storage. This is used in [Netlenium.Driver.Chrome.DriverManager](https://github.com/intellivoid/Netlenium/blob/master/Netlenium/Netlenium.Driver/Chrome/DriverManager.c)

as @mdelahozl said, we can forward the file from Google Storage to our CDN, and then from our distribution networks to the end-user.

This will result in better stability and independence.

**Comment by Netkas** [comment]
> > See [Netlenium.WebAPI.Google](https://github.com/intellivoid/Netlenium/tree/master/Netlenium/Netlenium.WebAPI/Google) as an example of how resources get retrieved from Google Storage. This is used in [Netlenium.Driver.Chrome.DriverManager](https://github.com/intellivoid/Netlenium/blob/master/Netlenium/Netlenium.Driver/Chrome/DriverManager.c)
> 
> as @mdelahozl said, we can forward the file from Google Storage to our CDN, and then from our distribution networks to the end-user.
> 
> This will result in better stability and independence.

This can work but this won't just involve Google but GitHub as well (Releases)

**Comment by Netkas** [comment]
See commit [35350663f418504b77752d68a4538d5cfcef50d9](https://github.com/intellivoid/Netlenium/commit/35350663f418504b77752d68a4538d5cfcef50d9)
